// Code generated by gen-go-client. DO NOT EDIT.
//
// IR source: dsl/domain/list-work-items.lisp
// IR sha256: bef58978256fe9f19af16f3d539041c168d2210c7a96c4a72e31eb43e3a32b0b
// IR kind:   query

package contracts

// ListWorkItemsQueryName is the GraphQL wire identifier for the list-work-items query.
const ListWorkItemsQueryName = "workItems"

// ListWorkItemsResult is the result element collection for the list-work-items query.
type ListWorkItemsResult = []WorkItem
