// Code generated by gen-go-client. DO NOT EDIT.
//
// IR source: dsl/domain/work-item.lisp
// IR sha256: 85dac41ffb84398e04b9de7c7237bd83afd8195883f2bf51342bbbee8d11b91f
// IR kind:   aggregate

package contracts

type WorkItem struct {
	Id    string `json:"id"`
	Title string `json:"title"`
	State string `json:"state"`
}
