// Code generated by gen-go-client. DO NOT EDIT.
//
// IR source: dsl/domain/work-item-created.lisp
// IR sha256: a96935c11b7d935788222a9a211ebfbed435b26f2bc13f68a2386291f45fb15a
// IR kind:   event

package contracts

type WorkItemCreated struct {
	WorkItemId string `json:"work_item_id"`
	Title      string `json:"title"`
}

// WorkItemCreatedEventName is the wire identifier emitted in SSE payloads for WorkItemCreated.
const WorkItemCreatedEventName = "work-item-created"
